// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChartItemsColumns holds the columns for the "chart_items" table.
	ChartItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeFloat64},
	}
	// ChartItemsTable holds the schema information for the "chart_items" table.
	ChartItemsTable = &schema.Table{
		Name:       "chart_items",
		Columns:    ChartItemsColumns,
		PrimaryKey: []*schema.Column{ChartItemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChartItemsTable,
	}
)

func init() {
}
