// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/euroquote"
	"main/ent/predicate"
	"main/ent/rubquote"
	"main/ent/uahquote"
	"main/ent/usdquote"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEUROQuote = "EUROQuote"
	TypeRUBQuote  = "RUBQuote"
	TypeUAHQuote  = "UAHQuote"
	TypeUSDQuote  = "USDQuote"
)

// EUROQuoteMutation represents an operation that mutates the EUROQuote nodes in the graph.
type EUROQuoteMutation struct {
	config
	op            Op
	typ           string
	id            *int
	price         *float64
	addprice      *float64
	_Timestamp    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*EUROQuote, error)
	predicates    []predicate.EUROQuote
}

var _ ent.Mutation = (*EUROQuoteMutation)(nil)

// euroquoteOption allows management of the mutation configuration using functional options.
type euroquoteOption func(*EUROQuoteMutation)

// newEUROQuoteMutation creates new mutation for the EUROQuote entity.
func newEUROQuoteMutation(c config, op Op, opts ...euroquoteOption) *EUROQuoteMutation {
	m := &EUROQuoteMutation{
		config:        c,
		op:            op,
		typ:           TypeEUROQuote,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEUROQuoteID sets the ID field of the mutation.
func withEUROQuoteID(id int) euroquoteOption {
	return func(m *EUROQuoteMutation) {
		var (
			err   error
			once  sync.Once
			value *EUROQuote
		)
		m.oldValue = func(ctx context.Context) (*EUROQuote, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().EUROQuote.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEUROQuote sets the old EUROQuote of the mutation.
func withEUROQuote(node *EUROQuote) euroquoteOption {
	return func(m *EUROQuoteMutation) {
		m.oldValue = func(context.Context) (*EUROQuote, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EUROQuoteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EUROQuoteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of EUROQuote entities.
func (m *EUROQuoteMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EUROQuoteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EUROQuoteMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().EUROQuote.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrice sets the "price" field.
func (m *EUROQuoteMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *EUROQuoteMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the EUROQuote entity.
// If the EUROQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EUROQuoteMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *EUROQuoteMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *EUROQuoteMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *EUROQuoteMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetTimestamp sets the "Timestamp" field.
func (m *EUROQuoteMutation) SetTimestamp(t time.Time) {
	m._Timestamp = &t
}

// Timestamp returns the value of the "Timestamp" field in the mutation.
func (m *EUROQuoteMutation) Timestamp() (r time.Time, exists bool) {
	v := m._Timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "Timestamp" field's value of the EUROQuote entity.
// If the EUROQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EUROQuoteMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "Timestamp" field.
func (m *EUROQuoteMutation) ResetTimestamp() {
	m._Timestamp = nil
}

// Where appends a list predicates to the EUROQuoteMutation builder.
func (m *EUROQuoteMutation) Where(ps ...predicate.EUROQuote) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *EUROQuoteMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (EUROQuote).
func (m *EUROQuoteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EUROQuoteMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.price != nil {
		fields = append(fields, euroquote.FieldPrice)
	}
	if m._Timestamp != nil {
		fields = append(fields, euroquote.FieldTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EUROQuoteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case euroquote.FieldPrice:
		return m.Price()
	case euroquote.FieldTimestamp:
		return m.Timestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EUROQuoteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case euroquote.FieldPrice:
		return m.OldPrice(ctx)
	case euroquote.FieldTimestamp:
		return m.OldTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown EUROQuote field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EUROQuoteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case euroquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case euroquote.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown EUROQuote field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EUROQuoteMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, euroquote.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EUROQuoteMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case euroquote.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EUROQuoteMutation) AddField(name string, value ent.Value) error {
	switch name {
	case euroquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown EUROQuote numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EUROQuoteMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EUROQuoteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EUROQuoteMutation) ClearField(name string) error {
	return fmt.Errorf("unknown EUROQuote nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EUROQuoteMutation) ResetField(name string) error {
	switch name {
	case euroquote.FieldPrice:
		m.ResetPrice()
		return nil
	case euroquote.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	}
	return fmt.Errorf("unknown EUROQuote field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EUROQuoteMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EUROQuoteMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EUROQuoteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EUROQuoteMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EUROQuoteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EUROQuoteMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EUROQuoteMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown EUROQuote unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EUROQuoteMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown EUROQuote edge %s", name)
}

// RUBQuoteMutation represents an operation that mutates the RUBQuote nodes in the graph.
type RUBQuoteMutation struct {
	config
	op            Op
	typ           string
	id            *int
	price         *float64
	addprice      *float64
	_Timestamp    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RUBQuote, error)
	predicates    []predicate.RUBQuote
}

var _ ent.Mutation = (*RUBQuoteMutation)(nil)

// rubquoteOption allows management of the mutation configuration using functional options.
type rubquoteOption func(*RUBQuoteMutation)

// newRUBQuoteMutation creates new mutation for the RUBQuote entity.
func newRUBQuoteMutation(c config, op Op, opts ...rubquoteOption) *RUBQuoteMutation {
	m := &RUBQuoteMutation{
		config:        c,
		op:            op,
		typ:           TypeRUBQuote,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRUBQuoteID sets the ID field of the mutation.
func withRUBQuoteID(id int) rubquoteOption {
	return func(m *RUBQuoteMutation) {
		var (
			err   error
			once  sync.Once
			value *RUBQuote
		)
		m.oldValue = func(ctx context.Context) (*RUBQuote, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RUBQuote.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRUBQuote sets the old RUBQuote of the mutation.
func withRUBQuote(node *RUBQuote) rubquoteOption {
	return func(m *RUBQuoteMutation) {
		m.oldValue = func(context.Context) (*RUBQuote, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RUBQuoteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RUBQuoteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RUBQuote entities.
func (m *RUBQuoteMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RUBQuoteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RUBQuoteMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RUBQuote.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrice sets the "price" field.
func (m *RUBQuoteMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *RUBQuoteMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the RUBQuote entity.
// If the RUBQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RUBQuoteMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *RUBQuoteMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *RUBQuoteMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *RUBQuoteMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetTimestamp sets the "Timestamp" field.
func (m *RUBQuoteMutation) SetTimestamp(t time.Time) {
	m._Timestamp = &t
}

// Timestamp returns the value of the "Timestamp" field in the mutation.
func (m *RUBQuoteMutation) Timestamp() (r time.Time, exists bool) {
	v := m._Timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "Timestamp" field's value of the RUBQuote entity.
// If the RUBQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RUBQuoteMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "Timestamp" field.
func (m *RUBQuoteMutation) ResetTimestamp() {
	m._Timestamp = nil
}

// Where appends a list predicates to the RUBQuoteMutation builder.
func (m *RUBQuoteMutation) Where(ps ...predicate.RUBQuote) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *RUBQuoteMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (RUBQuote).
func (m *RUBQuoteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RUBQuoteMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.price != nil {
		fields = append(fields, rubquote.FieldPrice)
	}
	if m._Timestamp != nil {
		fields = append(fields, rubquote.FieldTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RUBQuoteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rubquote.FieldPrice:
		return m.Price()
	case rubquote.FieldTimestamp:
		return m.Timestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RUBQuoteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rubquote.FieldPrice:
		return m.OldPrice(ctx)
	case rubquote.FieldTimestamp:
		return m.OldTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown RUBQuote field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RUBQuoteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rubquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case rubquote.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown RUBQuote field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RUBQuoteMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, rubquote.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RUBQuoteMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case rubquote.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RUBQuoteMutation) AddField(name string, value ent.Value) error {
	switch name {
	case rubquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown RUBQuote numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RUBQuoteMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RUBQuoteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RUBQuoteMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RUBQuote nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RUBQuoteMutation) ResetField(name string) error {
	switch name {
	case rubquote.FieldPrice:
		m.ResetPrice()
		return nil
	case rubquote.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	}
	return fmt.Errorf("unknown RUBQuote field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RUBQuoteMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RUBQuoteMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RUBQuoteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RUBQuoteMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RUBQuoteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RUBQuoteMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RUBQuoteMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RUBQuote unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RUBQuoteMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RUBQuote edge %s", name)
}

// UAHQuoteMutation represents an operation that mutates the UAHQuote nodes in the graph.
type UAHQuoteMutation struct {
	config
	op            Op
	typ           string
	id            *int
	price         *float64
	addprice      *float64
	_Timestamp    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UAHQuote, error)
	predicates    []predicate.UAHQuote
}

var _ ent.Mutation = (*UAHQuoteMutation)(nil)

// uahquoteOption allows management of the mutation configuration using functional options.
type uahquoteOption func(*UAHQuoteMutation)

// newUAHQuoteMutation creates new mutation for the UAHQuote entity.
func newUAHQuoteMutation(c config, op Op, opts ...uahquoteOption) *UAHQuoteMutation {
	m := &UAHQuoteMutation{
		config:        c,
		op:            op,
		typ:           TypeUAHQuote,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUAHQuoteID sets the ID field of the mutation.
func withUAHQuoteID(id int) uahquoteOption {
	return func(m *UAHQuoteMutation) {
		var (
			err   error
			once  sync.Once
			value *UAHQuote
		)
		m.oldValue = func(ctx context.Context) (*UAHQuote, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UAHQuote.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUAHQuote sets the old UAHQuote of the mutation.
func withUAHQuote(node *UAHQuote) uahquoteOption {
	return func(m *UAHQuoteMutation) {
		m.oldValue = func(context.Context) (*UAHQuote, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UAHQuoteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UAHQuoteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of UAHQuote entities.
func (m *UAHQuoteMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UAHQuoteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UAHQuoteMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UAHQuote.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrice sets the "price" field.
func (m *UAHQuoteMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *UAHQuoteMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the UAHQuote entity.
// If the UAHQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UAHQuoteMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *UAHQuoteMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *UAHQuoteMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *UAHQuoteMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetTimestamp sets the "Timestamp" field.
func (m *UAHQuoteMutation) SetTimestamp(t time.Time) {
	m._Timestamp = &t
}

// Timestamp returns the value of the "Timestamp" field in the mutation.
func (m *UAHQuoteMutation) Timestamp() (r time.Time, exists bool) {
	v := m._Timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "Timestamp" field's value of the UAHQuote entity.
// If the UAHQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UAHQuoteMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "Timestamp" field.
func (m *UAHQuoteMutation) ResetTimestamp() {
	m._Timestamp = nil
}

// Where appends a list predicates to the UAHQuoteMutation builder.
func (m *UAHQuoteMutation) Where(ps ...predicate.UAHQuote) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *UAHQuoteMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (UAHQuote).
func (m *UAHQuoteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UAHQuoteMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.price != nil {
		fields = append(fields, uahquote.FieldPrice)
	}
	if m._Timestamp != nil {
		fields = append(fields, uahquote.FieldTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UAHQuoteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case uahquote.FieldPrice:
		return m.Price()
	case uahquote.FieldTimestamp:
		return m.Timestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UAHQuoteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case uahquote.FieldPrice:
		return m.OldPrice(ctx)
	case uahquote.FieldTimestamp:
		return m.OldTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown UAHQuote field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UAHQuoteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case uahquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case uahquote.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown UAHQuote field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UAHQuoteMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, uahquote.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UAHQuoteMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case uahquote.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UAHQuoteMutation) AddField(name string, value ent.Value) error {
	switch name {
	case uahquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown UAHQuote numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UAHQuoteMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UAHQuoteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UAHQuoteMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UAHQuote nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UAHQuoteMutation) ResetField(name string) error {
	switch name {
	case uahquote.FieldPrice:
		m.ResetPrice()
		return nil
	case uahquote.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	}
	return fmt.Errorf("unknown UAHQuote field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UAHQuoteMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UAHQuoteMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UAHQuoteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UAHQuoteMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UAHQuoteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UAHQuoteMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UAHQuoteMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UAHQuote unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UAHQuoteMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UAHQuote edge %s", name)
}

// USDQuoteMutation represents an operation that mutates the USDQuote nodes in the graph.
type USDQuoteMutation struct {
	config
	op            Op
	typ           string
	id            *int
	price         *float64
	addprice      *float64
	_Timestamp    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*USDQuote, error)
	predicates    []predicate.USDQuote
}

var _ ent.Mutation = (*USDQuoteMutation)(nil)

// usdquoteOption allows management of the mutation configuration using functional options.
type usdquoteOption func(*USDQuoteMutation)

// newUSDQuoteMutation creates new mutation for the USDQuote entity.
func newUSDQuoteMutation(c config, op Op, opts ...usdquoteOption) *USDQuoteMutation {
	m := &USDQuoteMutation{
		config:        c,
		op:            op,
		typ:           TypeUSDQuote,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUSDQuoteID sets the ID field of the mutation.
func withUSDQuoteID(id int) usdquoteOption {
	return func(m *USDQuoteMutation) {
		var (
			err   error
			once  sync.Once
			value *USDQuote
		)
		m.oldValue = func(ctx context.Context) (*USDQuote, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().USDQuote.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUSDQuote sets the old USDQuote of the mutation.
func withUSDQuote(node *USDQuote) usdquoteOption {
	return func(m *USDQuoteMutation) {
		m.oldValue = func(context.Context) (*USDQuote, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m USDQuoteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m USDQuoteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of USDQuote entities.
func (m *USDQuoteMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *USDQuoteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *USDQuoteMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().USDQuote.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPrice sets the "price" field.
func (m *USDQuoteMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *USDQuoteMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the USDQuote entity.
// If the USDQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *USDQuoteMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *USDQuoteMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *USDQuoteMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *USDQuoteMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// SetTimestamp sets the "Timestamp" field.
func (m *USDQuoteMutation) SetTimestamp(t time.Time) {
	m._Timestamp = &t
}

// Timestamp returns the value of the "Timestamp" field in the mutation.
func (m *USDQuoteMutation) Timestamp() (r time.Time, exists bool) {
	v := m._Timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "Timestamp" field's value of the USDQuote entity.
// If the USDQuote object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *USDQuoteMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "Timestamp" field.
func (m *USDQuoteMutation) ResetTimestamp() {
	m._Timestamp = nil
}

// Where appends a list predicates to the USDQuoteMutation builder.
func (m *USDQuoteMutation) Where(ps ...predicate.USDQuote) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *USDQuoteMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (USDQuote).
func (m *USDQuoteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *USDQuoteMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.price != nil {
		fields = append(fields, usdquote.FieldPrice)
	}
	if m._Timestamp != nil {
		fields = append(fields, usdquote.FieldTimestamp)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *USDQuoteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case usdquote.FieldPrice:
		return m.Price()
	case usdquote.FieldTimestamp:
		return m.Timestamp()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *USDQuoteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case usdquote.FieldPrice:
		return m.OldPrice(ctx)
	case usdquote.FieldTimestamp:
		return m.OldTimestamp(ctx)
	}
	return nil, fmt.Errorf("unknown USDQuote field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *USDQuoteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case usdquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	case usdquote.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	}
	return fmt.Errorf("unknown USDQuote field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *USDQuoteMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, usdquote.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *USDQuoteMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case usdquote.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *USDQuoteMutation) AddField(name string, value ent.Value) error {
	switch name {
	case usdquote.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown USDQuote numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *USDQuoteMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *USDQuoteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *USDQuoteMutation) ClearField(name string) error {
	return fmt.Errorf("unknown USDQuote nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *USDQuoteMutation) ResetField(name string) error {
	switch name {
	case usdquote.FieldPrice:
		m.ResetPrice()
		return nil
	case usdquote.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	}
	return fmt.Errorf("unknown USDQuote field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *USDQuoteMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *USDQuoteMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *USDQuoteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *USDQuoteMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *USDQuoteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *USDQuoteMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *USDQuoteMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown USDQuote unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *USDQuoteMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown USDQuote edge %s", name)
}
