// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/rubchart"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RUBChartQuery is the builder for querying RUBChart entities.
type RUBChartQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RUBChart
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RUBChartQuery builder.
func (rcq *RUBChartQuery) Where(ps ...predicate.RUBChart) *RUBChartQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit adds a limit step to the query.
func (rcq *RUBChartQuery) Limit(limit int) *RUBChartQuery {
	rcq.limit = &limit
	return rcq
}

// Offset adds an offset step to the query.
func (rcq *RUBChartQuery) Offset(offset int) *RUBChartQuery {
	rcq.offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *RUBChartQuery) Unique(unique bool) *RUBChartQuery {
	rcq.unique = &unique
	return rcq
}

// Order adds an order step to the query.
func (rcq *RUBChartQuery) Order(o ...OrderFunc) *RUBChartQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// First returns the first RUBChart entity from the query.
// Returns a *NotFoundError when no RUBChart was found.
func (rcq *RUBChartQuery) First(ctx context.Context) (*RUBChart, error) {
	nodes, err := rcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rubchart.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *RUBChartQuery) FirstX(ctx context.Context) *RUBChart {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RUBChart ID from the query.
// Returns a *NotFoundError when no RUBChart ID was found.
func (rcq *RUBChartQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rubchart.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *RUBChartQuery) FirstIDX(ctx context.Context) int {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RUBChart entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RUBChart entity is found.
// Returns a *NotFoundError when no RUBChart entities are found.
func (rcq *RUBChartQuery) Only(ctx context.Context) (*RUBChart, error) {
	nodes, err := rcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rubchart.Label}
	default:
		return nil, &NotSingularError{rubchart.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *RUBChartQuery) OnlyX(ctx context.Context) *RUBChart {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RUBChart ID in the query.
// Returns a *NotSingularError when more than one RUBChart ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *RUBChartQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = &NotSingularError{rubchart.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *RUBChartQuery) OnlyIDX(ctx context.Context) int {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RUBCharts.
func (rcq *RUBChartQuery) All(ctx context.Context) ([]*RUBChart, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rcq *RUBChartQuery) AllX(ctx context.Context) []*RUBChart {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RUBChart IDs.
func (rcq *RUBChartQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rcq.Select(rubchart.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *RUBChartQuery) IDsX(ctx context.Context) []int {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *RUBChartQuery) Count(ctx context.Context) (int, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *RUBChartQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *RUBChartQuery) Exist(ctx context.Context) (bool, error) {
	if err := rcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *RUBChartQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RUBChartQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *RUBChartQuery) Clone() *RUBChartQuery {
	if rcq == nil {
		return nil
	}
	return &RUBChartQuery{
		config:     rcq.config,
		limit:      rcq.limit,
		offset:     rcq.offset,
		order:      append([]OrderFunc{}, rcq.order...),
		predicates: append([]predicate.RUBChart{}, rcq.predicates...),
		// clone intermediate query.
		sql:    rcq.sql.Clone(),
		path:   rcq.path,
		unique: rcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RUBChart.Query().
//		GroupBy(rubchart.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rcq *RUBChartQuery) GroupBy(field string, fields ...string) *RUBChartGroupBy {
	group := &RUBChartGroupBy{config: rcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.RUBChart.Query().
//		Select(rubchart.FieldPrice).
//		Scan(ctx, &v)
//
func (rcq *RUBChartQuery) Select(fields ...string) *RUBChartSelect {
	rcq.fields = append(rcq.fields, fields...)
	return &RUBChartSelect{RUBChartQuery: rcq}
}

func (rcq *RUBChartQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rcq.fields {
		if !rubchart.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *RUBChartQuery) sqlAll(ctx context.Context) ([]*RUBChart, error) {
	var (
		nodes = []*RUBChart{}
		_spec = rcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &RUBChart{config: rcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rcq *RUBChartQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	_spec.Node.Columns = rcq.fields
	if len(rcq.fields) > 0 {
		_spec.Unique = rcq.unique != nil && *rcq.unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *RUBChartQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rcq *RUBChartQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rubchart.Table,
			Columns: rubchart.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubchart.FieldID,
			},
		},
		From:   rcq.sql,
		Unique: true,
	}
	if unique := rcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rubchart.FieldID)
		for i := range fields {
			if fields[i] != rubchart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *RUBChartQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(rubchart.Table)
	columns := rcq.fields
	if len(columns) == 0 {
		columns = rubchart.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.unique != nil && *rcq.unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RUBChartGroupBy is the group-by builder for RUBChart entities.
type RUBChartGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *RUBChartGroupBy) Aggregate(fns ...AggregateFunc) *RUBChartGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rcgb *RUBChartGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rcgb.path(ctx)
	if err != nil {
		return err
	}
	rcgb.sql = query
	return rcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rcgb.fields) > 1 {
		return nil, errors.New("ent: RUBChartGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) StringsX(ctx context.Context) []string {
	v, err := rcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) StringX(ctx context.Context) string {
	v, err := rcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rcgb.fields) > 1 {
		return nil, errors.New("ent: RUBChartGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) IntsX(ctx context.Context) []int {
	v, err := rcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) IntX(ctx context.Context) int {
	v, err := rcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rcgb.fields) > 1 {
		return nil, errors.New("ent: RUBChartGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rcgb.fields) > 1 {
		return nil, errors.New("ent: RUBChartGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rcgb *RUBChartGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rcgb *RUBChartGroupBy) BoolX(ctx context.Context) bool {
	v, err := rcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rcgb *RUBChartGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rcgb.fields {
		if !rubchart.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rcgb *RUBChartGroupBy) sqlQuery() *sql.Selector {
	selector := rcgb.sql.Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rcgb.fields)+len(rcgb.fns))
		for _, f := range rcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rcgb.fields...)...)
}

// RUBChartSelect is the builder for selecting fields of RUBChart entities.
type RUBChartSelect struct {
	*RUBChartQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *RUBChartSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	rcs.sql = rcs.RUBChartQuery.sqlQuery(ctx)
	return rcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rcs *RUBChartSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rcs.fields) > 1 {
		return nil, errors.New("ent: RUBChartSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rcs *RUBChartSelect) StringsX(ctx context.Context) []string {
	v, err := rcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rcs *RUBChartSelect) StringX(ctx context.Context) string {
	v, err := rcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rcs.fields) > 1 {
		return nil, errors.New("ent: RUBChartSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rcs *RUBChartSelect) IntsX(ctx context.Context) []int {
	v, err := rcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rcs *RUBChartSelect) IntX(ctx context.Context) int {
	v, err := rcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rcs.fields) > 1 {
		return nil, errors.New("ent: RUBChartSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rcs *RUBChartSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rcs *RUBChartSelect) Float64X(ctx context.Context) float64 {
	v, err := rcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rcs.fields) > 1 {
		return nil, errors.New("ent: RUBChartSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rcs *RUBChartSelect) BoolsX(ctx context.Context) []bool {
	v, err := rcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (rcs *RUBChartSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{rubchart.Label}
	default:
		err = fmt.Errorf("ent: RUBChartSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rcs *RUBChartSelect) BoolX(ctx context.Context) bool {
	v, err := rcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rcs *RUBChartSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rcs.sql.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
