// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/rubchart"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RUBChartCreate is the builder for creating a RUBChart entity.
type RUBChartCreate struct {
	config
	mutation *RUBChartMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (rcc *RUBChartCreate) SetPrice(f float64) *RUBChartCreate {
	rcc.mutation.SetPrice(f)
	return rcc
}

// SetTimestamp sets the "Timestamp" field.
func (rcc *RUBChartCreate) SetTimestamp(t time.Time) *RUBChartCreate {
	rcc.mutation.SetTimestamp(t)
	return rcc
}

// SetID sets the "id" field.
func (rcc *RUBChartCreate) SetID(i int) *RUBChartCreate {
	rcc.mutation.SetID(i)
	return rcc
}

// Mutation returns the RUBChartMutation object of the builder.
func (rcc *RUBChartCreate) Mutation() *RUBChartMutation {
	return rcc.mutation
}

// Save creates the RUBChart in the database.
func (rcc *RUBChartCreate) Save(ctx context.Context) (*RUBChart, error) {
	var (
		err  error
		node *RUBChart
	)
	if len(rcc.hooks) == 0 {
		if err = rcc.check(); err != nil {
			return nil, err
		}
		node, err = rcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RUBChartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rcc.check(); err != nil {
				return nil, err
			}
			rcc.mutation = mutation
			if node, err = rcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rcc.hooks) - 1; i >= 0; i-- {
			if rcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rcc *RUBChartCreate) SaveX(ctx context.Context) *RUBChart {
	v, err := rcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcc *RUBChartCreate) Exec(ctx context.Context) error {
	_, err := rcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcc *RUBChartCreate) ExecX(ctx context.Context) {
	if err := rcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rcc *RUBChartCreate) check() error {
	if _, ok := rcc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "RUBChart.price"`)}
	}
	if _, ok := rcc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "Timestamp", err: errors.New(`ent: missing required field "RUBChart.Timestamp"`)}
	}
	return nil
}

func (rcc *RUBChartCreate) sqlSave(ctx context.Context) (*RUBChart, error) {
	_node, _spec := rcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (rcc *RUBChartCreate) createSpec() (*RUBChart, *sqlgraph.CreateSpec) {
	var (
		_node = &RUBChart{config: rcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: rubchart.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubchart.FieldID,
			},
		}
	)
	if id, ok := rcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rcc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: rubchart.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := rcc.mutation.Timestamp(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: rubchart.FieldTimestamp,
		})
		_node.Timestamp = value
	}
	return _node, _spec
}

// RUBChartCreateBulk is the builder for creating many RUBChart entities in bulk.
type RUBChartCreateBulk struct {
	config
	builders []*RUBChartCreate
}

// Save creates the RUBChart entities in the database.
func (rccb *RUBChartCreateBulk) Save(ctx context.Context) ([]*RUBChart, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rccb.builders))
	nodes := make([]*RUBChart, len(rccb.builders))
	mutators := make([]Mutator, len(rccb.builders))
	for i := range rccb.builders {
		func(i int, root context.Context) {
			builder := rccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RUBChartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rccb *RUBChartCreateBulk) SaveX(ctx context.Context) []*RUBChart {
	v, err := rccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rccb *RUBChartCreateBulk) Exec(ctx context.Context) error {
	_, err := rccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rccb *RUBChartCreateBulk) ExecX(ctx context.Context) {
	if err := rccb.Exec(ctx); err != nil {
		panic(err)
	}
}
