// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/predicate"
	"main/ent/rubchart"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RUBChartDelete is the builder for deleting a RUBChart entity.
type RUBChartDelete struct {
	config
	hooks    []Hook
	mutation *RUBChartMutation
}

// Where appends a list predicates to the RUBChartDelete builder.
func (rcd *RUBChartDelete) Where(ps ...predicate.RUBChart) *RUBChartDelete {
	rcd.mutation.Where(ps...)
	return rcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rcd *RUBChartDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rcd.hooks) == 0 {
		affected, err = rcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RUBChartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rcd.mutation = mutation
			affected, err = rcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rcd.hooks) - 1; i >= 0; i-- {
			if rcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcd *RUBChartDelete) ExecX(ctx context.Context) int {
	n, err := rcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rcd *RUBChartDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rubchart.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rubchart.FieldID,
			},
		},
	}
	if ps := rcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rcd.driver, _spec)
}

// RUBChartDeleteOne is the builder for deleting a single RUBChart entity.
type RUBChartDeleteOne struct {
	rcd *RUBChartDelete
}

// Exec executes the deletion query.
func (rcdo *RUBChartDeleteOne) Exec(ctx context.Context) error {
	n, err := rcdo.rcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rubchart.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rcdo *RUBChartDeleteOne) ExecX(ctx context.Context) {
	rcdo.rcd.ExecX(ctx)
}
