// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/predicate"
	"main/ent/sadquote"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SADQuoteDelete is the builder for deleting a SADQuote entity.
type SADQuoteDelete struct {
	config
	hooks    []Hook
	mutation *SADQuoteMutation
}

// Where appends a list predicates to the SADQuoteDelete builder.
func (sqd *SADQuoteDelete) Where(ps ...predicate.SADQuote) *SADQuoteDelete {
	sqd.mutation.Where(ps...)
	return sqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sqd *SADQuoteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sqd.hooks) == 0 {
		affected, err = sqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SADQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sqd.mutation = mutation
			affected, err = sqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sqd.hooks) - 1; i >= 0; i-- {
			if sqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sqd *SADQuoteDelete) ExecX(ctx context.Context) int {
	n, err := sqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sqd *SADQuoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: sadquote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sadquote.FieldID,
			},
		},
	}
	if ps := sqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sqd.driver, _spec)
}

// SADQuoteDeleteOne is the builder for deleting a single SADQuote entity.
type SADQuoteDeleteOne struct {
	sqd *SADQuoteDelete
}

// Exec executes the deletion query.
func (sqdo *SADQuoteDeleteOne) Exec(ctx context.Context) error {
	n, err := sqdo.sqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sadquote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sqdo *SADQuoteDeleteOne) ExecX(ctx context.Context) {
	sqdo.sqd.ExecX(ctx)
}
