// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/sadquote"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SADQuoteUpdate is the builder for updating SADQuote entities.
type SADQuoteUpdate struct {
	config
	hooks    []Hook
	mutation *SADQuoteMutation
}

// Where appends a list predicates to the SADQuoteUpdate builder.
func (squ *SADQuoteUpdate) Where(ps ...predicate.SADQuote) *SADQuoteUpdate {
	squ.mutation.Where(ps...)
	return squ
}

// SetPrice sets the "price" field.
func (squ *SADQuoteUpdate) SetPrice(f float64) *SADQuoteUpdate {
	squ.mutation.ResetPrice()
	squ.mutation.SetPrice(f)
	return squ
}

// AddPrice adds f to the "price" field.
func (squ *SADQuoteUpdate) AddPrice(f float64) *SADQuoteUpdate {
	squ.mutation.AddPrice(f)
	return squ
}

// SetTimestamp sets the "Timestamp" field.
func (squ *SADQuoteUpdate) SetTimestamp(t time.Time) *SADQuoteUpdate {
	squ.mutation.SetTimestamp(t)
	return squ
}

// Mutation returns the SADQuoteMutation object of the builder.
func (squ *SADQuoteUpdate) Mutation() *SADQuoteMutation {
	return squ.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (squ *SADQuoteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(squ.hooks) == 0 {
		affected, err = squ.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SADQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			squ.mutation = mutation
			affected, err = squ.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(squ.hooks) - 1; i >= 0; i-- {
			if squ.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = squ.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, squ.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (squ *SADQuoteUpdate) SaveX(ctx context.Context) int {
	affected, err := squ.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (squ *SADQuoteUpdate) Exec(ctx context.Context) error {
	_, err := squ.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (squ *SADQuoteUpdate) ExecX(ctx context.Context) {
	if err := squ.Exec(ctx); err != nil {
		panic(err)
	}
}

func (squ *SADQuoteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sadquote.Table,
			Columns: sadquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sadquote.FieldID,
			},
		},
	}
	if ps := squ.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := squ.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sadquote.FieldPrice,
		})
	}
	if value, ok := squ.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sadquote.FieldPrice,
		})
	}
	if value, ok := squ.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sadquote.FieldTimestamp,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, squ.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sadquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SADQuoteUpdateOne is the builder for updating a single SADQuote entity.
type SADQuoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SADQuoteMutation
}

// SetPrice sets the "price" field.
func (squo *SADQuoteUpdateOne) SetPrice(f float64) *SADQuoteUpdateOne {
	squo.mutation.ResetPrice()
	squo.mutation.SetPrice(f)
	return squo
}

// AddPrice adds f to the "price" field.
func (squo *SADQuoteUpdateOne) AddPrice(f float64) *SADQuoteUpdateOne {
	squo.mutation.AddPrice(f)
	return squo
}

// SetTimestamp sets the "Timestamp" field.
func (squo *SADQuoteUpdateOne) SetTimestamp(t time.Time) *SADQuoteUpdateOne {
	squo.mutation.SetTimestamp(t)
	return squo
}

// Mutation returns the SADQuoteMutation object of the builder.
func (squo *SADQuoteUpdateOne) Mutation() *SADQuoteMutation {
	return squo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (squo *SADQuoteUpdateOne) Select(field string, fields ...string) *SADQuoteUpdateOne {
	squo.fields = append([]string{field}, fields...)
	return squo
}

// Save executes the query and returns the updated SADQuote entity.
func (squo *SADQuoteUpdateOne) Save(ctx context.Context) (*SADQuote, error) {
	var (
		err  error
		node *SADQuote
	)
	if len(squo.hooks) == 0 {
		node, err = squo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SADQuoteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			squo.mutation = mutation
			node, err = squo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(squo.hooks) - 1; i >= 0; i-- {
			if squo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = squo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, squo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (squo *SADQuoteUpdateOne) SaveX(ctx context.Context) *SADQuote {
	node, err := squo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (squo *SADQuoteUpdateOne) Exec(ctx context.Context) error {
	_, err := squo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (squo *SADQuoteUpdateOne) ExecX(ctx context.Context) {
	if err := squo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (squo *SADQuoteUpdateOne) sqlSave(ctx context.Context) (_node *SADQuote, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sadquote.Table,
			Columns: sadquote.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sadquote.FieldID,
			},
		},
	}
	id, ok := squo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SADQuote.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := squo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sadquote.FieldID)
		for _, f := range fields {
			if !sadquote.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sadquote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := squo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := squo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sadquote.FieldPrice,
		})
	}
	if value, ok := squo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: sadquote.FieldPrice,
		})
	}
	if value, ok := squo.mutation.Timestamp(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: sadquote.FieldTimestamp,
		})
	}
	_node = &SADQuote{config: squo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, squo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sadquote.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
