// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"main/ent/predicate"
	"main/ent/usdchart"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// USDChartDelete is the builder for deleting a USDChart entity.
type USDChartDelete struct {
	config
	hooks    []Hook
	mutation *USDChartMutation
}

// Where appends a list predicates to the USDChartDelete builder.
func (ucd *USDChartDelete) Where(ps ...predicate.USDChart) *USDChartDelete {
	ucd.mutation.Where(ps...)
	return ucd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ucd *USDChartDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ucd.hooks) == 0 {
		affected, err = ucd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*USDChartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ucd.mutation = mutation
			affected, err = ucd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ucd.hooks) - 1; i >= 0; i-- {
			if ucd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ucd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ucd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucd *USDChartDelete) ExecX(ctx context.Context) int {
	n, err := ucd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ucd *USDChartDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usdchart.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usdchart.FieldID,
			},
		},
	}
	if ps := ucd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ucd.driver, _spec)
}

// USDChartDeleteOne is the builder for deleting a single USDChart entity.
type USDChartDeleteOne struct {
	ucd *USDChartDelete
}

// Exec executes the deletion query.
func (ucdo *USDChartDeleteOne) Exec(ctx context.Context) error {
	n, err := ucdo.ucd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usdchart.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ucdo *USDChartDeleteOne) ExecX(ctx context.Context) {
	ucdo.ucd.ExecX(ctx)
}
