// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"main/ent/predicate"
	"main/ent/usdchart"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// USDChartQuery is the builder for querying USDChart entities.
type USDChartQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.USDChart
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the USDChartQuery builder.
func (ucq *USDChartQuery) Where(ps ...predicate.USDChart) *USDChartQuery {
	ucq.predicates = append(ucq.predicates, ps...)
	return ucq
}

// Limit adds a limit step to the query.
func (ucq *USDChartQuery) Limit(limit int) *USDChartQuery {
	ucq.limit = &limit
	return ucq
}

// Offset adds an offset step to the query.
func (ucq *USDChartQuery) Offset(offset int) *USDChartQuery {
	ucq.offset = &offset
	return ucq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ucq *USDChartQuery) Unique(unique bool) *USDChartQuery {
	ucq.unique = &unique
	return ucq
}

// Order adds an order step to the query.
func (ucq *USDChartQuery) Order(o ...OrderFunc) *USDChartQuery {
	ucq.order = append(ucq.order, o...)
	return ucq
}

// First returns the first USDChart entity from the query.
// Returns a *NotFoundError when no USDChart was found.
func (ucq *USDChartQuery) First(ctx context.Context) (*USDChart, error) {
	nodes, err := ucq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usdchart.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ucq *USDChartQuery) FirstX(ctx context.Context) *USDChart {
	node, err := ucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first USDChart ID from the query.
// Returns a *NotFoundError when no USDChart ID was found.
func (ucq *USDChartQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ucq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usdchart.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ucq *USDChartQuery) FirstIDX(ctx context.Context) int {
	id, err := ucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single USDChart entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one USDChart entity is found.
// Returns a *NotFoundError when no USDChart entities are found.
func (ucq *USDChartQuery) Only(ctx context.Context) (*USDChart, error) {
	nodes, err := ucq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usdchart.Label}
	default:
		return nil, &NotSingularError{usdchart.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ucq *USDChartQuery) OnlyX(ctx context.Context) *USDChart {
	node, err := ucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only USDChart ID in the query.
// Returns a *NotSingularError when more than one USDChart ID is found.
// Returns a *NotFoundError when no entities are found.
func (ucq *USDChartQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ucq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = &NotSingularError{usdchart.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ucq *USDChartQuery) OnlyIDX(ctx context.Context) int {
	id, err := ucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of USDCharts.
func (ucq *USDChartQuery) All(ctx context.Context) ([]*USDChart, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ucq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ucq *USDChartQuery) AllX(ctx context.Context) []*USDChart {
	nodes, err := ucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of USDChart IDs.
func (ucq *USDChartQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ucq.Select(usdchart.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ucq *USDChartQuery) IDsX(ctx context.Context) []int {
	ids, err := ucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ucq *USDChartQuery) Count(ctx context.Context) (int, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ucq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ucq *USDChartQuery) CountX(ctx context.Context) int {
	count, err := ucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ucq *USDChartQuery) Exist(ctx context.Context) (bool, error) {
	if err := ucq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ucq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ucq *USDChartQuery) ExistX(ctx context.Context) bool {
	exist, err := ucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the USDChartQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ucq *USDChartQuery) Clone() *USDChartQuery {
	if ucq == nil {
		return nil
	}
	return &USDChartQuery{
		config:     ucq.config,
		limit:      ucq.limit,
		offset:     ucq.offset,
		order:      append([]OrderFunc{}, ucq.order...),
		predicates: append([]predicate.USDChart{}, ucq.predicates...),
		// clone intermediate query.
		sql:    ucq.sql.Clone(),
		path:   ucq.path,
		unique: ucq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.USDChart.Query().
//		GroupBy(usdchart.FieldPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ucq *USDChartQuery) GroupBy(field string, fields ...string) *USDChartGroupBy {
	group := &USDChartGroupBy{config: ucq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ucq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Price float64 `json:"price,omitempty"`
//	}
//
//	client.USDChart.Query().
//		Select(usdchart.FieldPrice).
//		Scan(ctx, &v)
//
func (ucq *USDChartQuery) Select(fields ...string) *USDChartSelect {
	ucq.fields = append(ucq.fields, fields...)
	return &USDChartSelect{USDChartQuery: ucq}
}

func (ucq *USDChartQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ucq.fields {
		if !usdchart.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ucq.path != nil {
		prev, err := ucq.path(ctx)
		if err != nil {
			return err
		}
		ucq.sql = prev
	}
	return nil
}

func (ucq *USDChartQuery) sqlAll(ctx context.Context) ([]*USDChart, error) {
	var (
		nodes = []*USDChart{}
		_spec = ucq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &USDChart{config: ucq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ucq *USDChartQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ucq.querySpec()
	_spec.Node.Columns = ucq.fields
	if len(ucq.fields) > 0 {
		_spec.Unique = ucq.unique != nil && *ucq.unique
	}
	return sqlgraph.CountNodes(ctx, ucq.driver, _spec)
}

func (ucq *USDChartQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ucq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ucq *USDChartQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usdchart.Table,
			Columns: usdchart.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usdchart.FieldID,
			},
		},
		From:   ucq.sql,
		Unique: true,
	}
	if unique := ucq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ucq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usdchart.FieldID)
		for i := range fields {
			if fields[i] != usdchart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ucq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ucq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ucq *USDChartQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ucq.driver.Dialect())
	t1 := builder.Table(usdchart.Table)
	columns := ucq.fields
	if len(columns) == 0 {
		columns = usdchart.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ucq.sql != nil {
		selector = ucq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ucq.unique != nil && *ucq.unique {
		selector.Distinct()
	}
	for _, p := range ucq.predicates {
		p(selector)
	}
	for _, p := range ucq.order {
		p(selector)
	}
	if offset := ucq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ucq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// USDChartGroupBy is the group-by builder for USDChart entities.
type USDChartGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ucgb *USDChartGroupBy) Aggregate(fns ...AggregateFunc) *USDChartGroupBy {
	ucgb.fns = append(ucgb.fns, fns...)
	return ucgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ucgb *USDChartGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ucgb.path(ctx)
	if err != nil {
		return err
	}
	ucgb.sql = query
	return ucgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ucgb *USDChartGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ucgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: USDChartGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ucgb *USDChartGroupBy) StringsX(ctx context.Context) []string {
	v, err := ucgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ucgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ucgb *USDChartGroupBy) StringX(ctx context.Context) string {
	v, err := ucgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: USDChartGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ucgb *USDChartGroupBy) IntsX(ctx context.Context) []int {
	v, err := ucgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ucgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ucgb *USDChartGroupBy) IntX(ctx context.Context) int {
	v, err := ucgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: USDChartGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ucgb *USDChartGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ucgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ucgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ucgb *USDChartGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ucgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ucgb.fields) > 1 {
		return nil, errors.New("ent: USDChartGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ucgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ucgb *USDChartGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ucgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ucgb *USDChartGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ucgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ucgb *USDChartGroupBy) BoolX(ctx context.Context) bool {
	v, err := ucgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ucgb *USDChartGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ucgb.fields {
		if !usdchart.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ucgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ucgb *USDChartGroupBy) sqlQuery() *sql.Selector {
	selector := ucgb.sql.Select()
	aggregation := make([]string, 0, len(ucgb.fns))
	for _, fn := range ucgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ucgb.fields)+len(ucgb.fns))
		for _, f := range ucgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ucgb.fields...)...)
}

// USDChartSelect is the builder for selecting fields of USDChart entities.
type USDChartSelect struct {
	*USDChartQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ucs *USDChartSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ucs.prepareQuery(ctx); err != nil {
		return err
	}
	ucs.sql = ucs.USDChartQuery.sqlQuery(ctx)
	return ucs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ucs *USDChartSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ucs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: USDChartSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ucs *USDChartSelect) StringsX(ctx context.Context) []string {
	v, err := ucs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ucs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ucs *USDChartSelect) StringX(ctx context.Context) string {
	v, err := ucs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: USDChartSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ucs *USDChartSelect) IntsX(ctx context.Context) []int {
	v, err := ucs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ucs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ucs *USDChartSelect) IntX(ctx context.Context) int {
	v, err := ucs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: USDChartSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ucs *USDChartSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ucs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ucs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ucs *USDChartSelect) Float64X(ctx context.Context) float64 {
	v, err := ucs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ucs.fields) > 1 {
		return nil, errors.New("ent: USDChartSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ucs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ucs *USDChartSelect) BoolsX(ctx context.Context) []bool {
	v, err := ucs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ucs *USDChartSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ucs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usdchart.Label}
	default:
		err = fmt.Errorf("ent: USDChartSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ucs *USDChartSelect) BoolX(ctx context.Context) bool {
	v, err := ucs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ucs *USDChartSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ucs.sql.Query()
	if err := ucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
