// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"main/ent/usdchart"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// USDChart is the model entity for the USDChart schema.
type USDChart struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Timestamp holds the value of the "Timestamp" field.
	Timestamp time.Time `json:"Timestamp,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*USDChart) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case usdchart.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case usdchart.FieldID:
			values[i] = new(sql.NullInt64)
		case usdchart.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type USDChart", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the USDChart fields.
func (uc *USDChart) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usdchart.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			uc.ID = int(value.Int64)
		case usdchart.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				uc.Price = value.Float64
			}
		case usdchart.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field Timestamp", values[i])
			} else if value.Valid {
				uc.Timestamp = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this USDChart.
// Note that you need to call USDChart.Unwrap() before calling this method if this USDChart
// was returned from a transaction, and the transaction was committed or rolled back.
func (uc *USDChart) Update() *USDChartUpdateOne {
	return (&USDChartClient{config: uc.config}).UpdateOne(uc)
}

// Unwrap unwraps the USDChart entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (uc *USDChart) Unwrap() *USDChart {
	tx, ok := uc.config.driver.(*txDriver)
	if !ok {
		panic("ent: USDChart is not a transactional entity")
	}
	uc.config.driver = tx.drv
	return uc
}

// String implements the fmt.Stringer.
func (uc *USDChart) String() string {
	var builder strings.Builder
	builder.WriteString("USDChart(")
	builder.WriteString(fmt.Sprintf("id=%v", uc.ID))
	builder.WriteString(", price=")
	builder.WriteString(fmt.Sprintf("%v", uc.Price))
	builder.WriteString(", Timestamp=")
	builder.WriteString(uc.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// USDCharts is a parsable slice of USDChart.
type USDCharts []*USDChart

func (uc USDCharts) config(cfg config) {
	for _i := range uc {
		uc[_i].config = cfg
	}
}
