// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EUROQuote is the predicate function for euroquote builders.
type EUROQuote func(*sql.Selector)

// RUBQuote is the predicate function for rubquote builders.
type RUBQuote func(*sql.Selector)

// UAHQuote is the predicate function for uahquote builders.
type UAHQuote func(*sql.Selector)

// USDQuote is the predicate function for usdquote builders.
type USDQuote func(*sql.Selector)
