// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AUDQuote is the predicate function for audquote builders.
type AUDQuote func(*sql.Selector)

// EUROQuote is the predicate function for euroquote builders.
type EUROQuote func(*sql.Selector)

// GBPQuote is the predicate function for gbpquote builders.
type GBPQuote func(*sql.Selector)

// INRQuote is the predicate function for inrquote builders.
type INRQuote func(*sql.Selector)

// NZDQuote is the predicate function for nzdquote builders.
type NZDQuote func(*sql.Selector)

// PKRQuote is the predicate function for pkrquote builders.
type PKRQuote func(*sql.Selector)

// RUBQuote is the predicate function for rubquote builders.
type RUBQuote func(*sql.Selector)

// UAHQuote is the predicate function for uahquote builders.
type UAHQuote func(*sql.Selector)

// USDQuote is the predicate function for usdquote builders.
type USDQuote func(*sql.Selector)

// ZARQuote is the predicate function for zarquote builders.
type ZARQuote func(*sql.Selector)
