// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RUBChart is the predicate function for rubchart builders.
type RUBChart func(*sql.Selector)

// USDChart is the predicate function for usdchart builders.
type USDChart func(*sql.Selector)
